config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :artists
  end

  resources :artists, only: [:index, :show]
  resources :locations, only: [:index, :show]
  resources :media, only: [:index, :show]


  get '/home', to: 'home#index'
  get '/documentation', to: 'documentation#index'

  root to: "home#index"

  get '/home/:id', to: 'home#show', as: "artist_show"

  #static routes
  get '/documentation/artists/get_a_specific_artist', to: 'documentation#get_a_specific_artist'
  get '/documentation/artists/listing_artists', to: 'documentation#listing_artists'
  get '/documentation/locations/get_a_specific_location', to: 'documentation#get_a_specific_location'
  get '/documentation/locations/listing_locations', to: 'documentation#listing_locations'
  get '/documentation/media/get_a_specific_medium', to: 'documentation#get_a_specific_medium'
  get '/documentation/media/listing_media', to: 'documentation#listing_media'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  include PgSearch 
  has_many :artist_media
  has_many :media, through: :artist_media
  has_many :artist_locations
  has_many :locations, through: :artist_locations 
  has_one_attached :image
  pg_search_scope :search_artists, :against => :name, :associated_against => {
    :media => :name
  }

  accepts_nested_attributes_for :media

  def self.create_seeds
    seeds = ""
    all.each do |artist|
      seeds << "Artist.create!(name: '#{artist.name}', location: '#{artist.location}', gender: '#{artist.gender}', age: '#{artist.age}', facebook: '#{artist.facebook}', tumblr: '#{artist.tumblr}', instagram: '#{artist.instagram}', twitter: '#{artist.twitter}')"
    end
    puts seeds
  end
end

app/models/artist_location.rb
class ArtistLocation < ApplicationRecord
  belongs_to :artist
  belongs_to :location 
end

app/models/artist_medium.rb
class ArtistMedium < ApplicationRecord
  belongs_to :artist
  belongs_to :medium
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :artist_locations
  has_many :artists, through: :artist_locations
  has_many :medium_locations
  has_many :media, through: :medium_locations
end

app/models/medium.rb
class Medium < ApplicationRecord
  has_many :artist_media
  has_many :artists, through: :artist_media
  has_many :medium_locations 
  has_many :locations, through: :medium_locations
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to admin_artists_path
    else
      flash[:errors] = @artist.errors.full_messages
      render :new
    end
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.media.destroy_all
    @artist.media = Medium.find(params[:media])
    if @artist.update(artist_params)
      redirect_to admin_artists_path
    else 
      flash[:errors] = @artist.errors.full_messages
      render :edit
    end
  end

  def edit 
    @artist = Artist.find(params[:id])
    @artist_media = @artist.media
  end

  def destroy
  end

private

  def artist_params
    params.require(:artist).permit(:instagram, :name, :gender, :age, :facebook, :tumblr, :twitter, :location, :image, :website)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @results = Artist.where(artist_params)
    render json: @results 
  end

  def show 
    @result = Artist.find(params[:id])
    render json: @result
  end

private

  def artist_params
  params.permit(:name, :gender, :age, :facebook, :instagram, :tumblr, :twitter)
  end

# create
# params[]
# if params are not empty
# create a new artists with name = params[:name]
end

app/controllers/documentation_controller.rb
class DocumentationController < ApplicationController
  def index
  end

  def get_a_specific_artist
  end

  def listing_artists
  end

  def get_a_specific_location
  end

  def listing_locations
  end

  def get_a_specific_medium
  end

  def listing_media
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:search_artists].present?
      @artists = Artist.search_artists(params[:search_artists]).page params[:page]
    else
      @artists = Artist.page params[:page]
    end
  end 

  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @results = Location.all
    render json: @results
  end

  def show
    @result = Location.find(params[:id])
    render json: @result
  end

# create
# params[]
# if params are not empty
# create a new artists with name = params[:name]
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  def index
    @results = Medium.all
    render json: @results
  end

  def show
    @result = Medium.find(params[:id])
    render json: @result
  end

# create
# params[]
# if params are not empty
# create a new artists with name = params[:name]
end

app/helpers/admin/artists_helper.rb
module Admin::ArtistsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/views/admin/artists/create.html.erb
<h1>Admin::Artists#create</h1>
<p>Find me in app/views/admin/artists/create.html.erb</p>

app/views/admin/artists/destroy.html.erb
<h1>Admin::Artists#destroy</h1>
<p>Find me in app/views/admin/artists/destroy.html.erb</p>

app/views/admin/artists/edit.html.erb
<h1>Admin::Artists#edit</h1>
<%= form_for @artist, url: admin_artist_path do |f| %>
  <%= flash[:errors] %>
  name: <%= f.text_field :name %>
  gender: <%= f.text_field :gender %>
  age: <%= f.text_field :age %>
  location: <%= f.text_field :location %>
  instagram: <%= f.text_field :instagram %>
  facebook: <%= f.text_field :facebook %>
  tumblr: <%= f.text_field :tumblr %>
  twitter: <%= f.text_field :twitter %>
  website: <%= f.text_field :website %>
  <% if @artist.image.attached? %>
    <%= image_tag @artist.image %>
  <% end %>  

  image: <%= f.file_field :image %> 
  <br>
  <% Medium.all.each do |medium| %>
    <%= f.label medium.name %>
    <% if @artist.media.include? medium  %>
      <%= check_box_tag "media[]", medium.id, checked: true %>
      <br>
    <% else %>
      <%= check_box_tag "media[]", medium.id %>  
      <br>
    <% end %>  
  <% end %>
  <%= f.submit %>
<% end %>

app/views/admin/artists/index.html.erb
<ul>
  <% @artists.each do |artist| %>
    <li>
      <%= artist.name %>
      <%= link_to "Edit", edit_admin_artist_path(artist) %>
    </li>
  <% end %>
</ul>

app/views/admin/artists/new.html.erb
<%= form_for @artist, url: admin_artists_path do |f| %>
  <%= flash[:errors] %>
  name: <%= f.text_field :name %>
  gender: <%= f.text_field :gender %>
  age: <%= f.text_field :age %>
  location: <%= f.text_field :location %>
  instagram: <%= f.text_field :instagram %>
  facebook: <%= f.text_field :facebook %>
  tumblr: <%= f.text_field :tumblr %>
  twitter: <%= f.text_field :twitter %>
  website: <%= f.text_field :website %>
  image: <%= f.file_field :image %> 
  <%= f.submit %>
<% end %>

app/views/admin/artists/show.html.erb
<h1>Admin::Artists#show</h1>
<p>Find me in app/views/admin/artists/show.html.erb</p>

app/views/admin/artists/update.html.erb
<h1>Admin::Artists#update</h1>
<p>Find me in app/views/admin/artists/update.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/documentation/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>API Documentation</title>
  <meta charset="utf-8">
  <style>
    
body {
  font-family: Helvetica,Arial,sans-serif;
  font-size: 13px;
  font-weight: normal;
  line-height: 18px;
  color: #f5f5f5;
}

.container {
  width: 940px;
  margin-left: auto;
  margin-right: auto;
  zoom: 1;
}

pre {
  background-color: #f5f5f5;
  display: block;
  padding: 8.5px;
  margin: 0 0 18px;
  line-height: 18px;
  font-size: 12px;
  border: 1px solid #ccc;
  border: 1px solid rgba(0, 0, 0, 0.15);
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
  white-space: pre;
  white-space: pre-wrap;
  word-wrap: break-word;
}

td.required .name:after {
  float: right;
  content: &quot;required&quot;;
  font-weight: normal;
  color: #F08080;
}

a{
  color: #95897C;
  text-decoration: none;
  line-height: inherit;
  font-weight: inherit;
}

h1, h2, h3, h4, h5, h6 {
  font-weight: bold;
  color: #f5f5f5;
}

h1 {
  margin-bottom: 18px;
  font-size: 30px;
  line-height: 36px;
}
h2 {
  font-size: 24px;
  line-height: 36px;
}
h3{
  font-size: 18px;
  line-height: 36px;
}
h4 {
  font-size: 16px;
  line-height: 36px;
}

table{
  width: 100%;
  margin-bottom: 18px;
  padding: 0;
  border-collapse: separate;
  font-size: 13px;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
  border-spacing: 0;
  border: 1px solid #ddd;
}

table th {
  padding-top: 9px;
  font-weight: bold;
  vertical-align: middle;
  border-bottom: 1px solid #ddd;
}
table th+th, table td+td {
  border-left: 1px solid #ddd;
}
table th, table td {
  padding: 10px 10px 9px;
  line-height: 18px;
  text-align: left;
}

  </style>
</head>
<body>
<div class="container">
  <h1>API Documentation</h1>
  <p class="explanation">
    Heart Black Art REST API consists of hand-curated works by black artists in the United States. This documentation will help you search and discover black artists and link you to their websites and social media accounts for future communications and art investments. 
  </p>
  
  <div class="article">
    <h2>Artists</h2>

      <p class="explanation">Fetch artists from the database based on optional parameters</p>

    <ul>
      <li>
        <a href="documentation/artists/get_a_specific_artist.html">Get a specific artist</a>
      </li>
      <li>
        <a href="documentation/artists/listing_artists.html">Listing artists</a>
      </li>
    </ul>
  </div>
  <div class="article">
    <h2>Locations</h2>

      <p class="explanation">Fetch locations from the database based on optional parameters</p>

    <ul>
      <li>
        <a href="documentation/locations/get_a_specific_location.html">Get a specific location</a>
      </li>
      <li>
        <a href="documentation/locations/listing_locations.html">Listing locations</a>
      </li>
    </ul>
  </div>
  <div class="article">
    <h2>Media</h2>

      <p class="explanation">Fetch media from the database based on optional parameters</p>

    <ul>
      <li>
        <a href="documentation/media/get_a_specific_medium.html">Get a specific medium</a>
      </li>
      <li>
        <a href="documentation/media/listing_media.html">Listing media</a>
      </li>
    </ul>
  </div>
</div>
</body>
</html>

app/views/home/index.html.erb
<div class="container">
  <div class="row"> 
    <div class="col-md-4 mt-3">
      <h1 class="display-5">❤️ Heart Black Art</h1>
      <h4 class="mt-5">A Database of Black Artists</h4>
      <p>
        A digital collection of artists, presented as a well-documented, thoroughly tested REST API.
      </p>
      <p>Try it below:</p>
      <%= form_tag("/home", method: "get") do %>
         <%= text_field_tag :search_artists, nil, placeholder: "ie. Acrylic" %>
         <%= submit_tag "Search" %>
      <% end %>

      <h4 class="mt-5" >Docs</h4>
      <p>Documentation can be found <%= link_to "here",documentation_path, style: 'color:#f5f5f5; text-decoration: underline' %>.</p>

      <p></p>
    </div>
    <div class="col-md-8">
      <div class="row image-grid">
        <% @artists.each do |artist| %>
            <!-- <h4> <%= artist.name %> </h4> -->
            <!-- <p>Location: <%= artist.location %> </p> -->
            <%# link_to "artist info", "https://google.com" %>
            <!-- <span>Media: <% artist.media.each do |media| %></span>
              <span><%= media.name %></span>
            <% end %> -->
              <% if artist.image.attached? %>
              <%= link_to artist_show_path(artist) do %>
               <%= image_tag artist.image, class: "image-grid-item", style: "width: 240px; float: right;" %>
              <% end %> 
            <% end %> 
        <% end %>
        <%= paginate @artists %>
      </div>
    </div>
  </div>
</div> 

app/views/home/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col text-right">
      <h4> <%= @artist.name %> </h4>
      <p><%= @artist.location %> </p>

      <% if @artist.website.present? %>
      <p><%= link_to "Website", @artist.website, target: 'blank', style: 'color:#f5f5f5' %><p>
        <% end %>

      <% if @artist.twitter.present? %>
        <p><%= link_to "Twitter", @artist.twitter, target: 'blank', style: 'color:#f5f5f5' %><p>
      <% end %>

      <% if @artist.instagram.present? %>
        <p><%= link_to "Instagram", @artist.instagram, target: 'blank', style: 'color:#f5f5f5' %><p>
      <% end %>

      <% if @artist.tumblr.present? %>
        <p><%= link_to "Tumblr", @artist.tumblr, target: 'blank', style: 'color:#f5f5f5' %><p>
      <% end %>

      <% if @artist.facebook.present? %>
        <p><%= link_to "Facebook", @artist.facebook, target: 'blank', style: 'color:#f5f5f5' %><p>
      <% end %>
      <ul class="list-unstyled">
        <h5><i>Media</i></h5>
        <% @artist.media.each do |media| %>
          <li ><%= media.name %></li>
        <% end %>
      </ul> 
    </div>
    <div class="col">
      <% if @artist.image.attached? %>
        <%= image_tag @artist.image, style: "width: 240px;" %>
      <% end %>  
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeartBlackArt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>

    <!-- application.html.erb in Head tag below turbolinks -->
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Locations#index</h1>
<p>Find me in app/views/locations/index.html.erb</p>

app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>

app/views/media/index.html.erb
<h1>Media#index</h1>
<p>Find me in app/views/media/index.html.erb</p>

app/views/media/show.html.erb
<h1>Media#show</h1>
<p>Find me in app/views/media/show.html.erb</p>